### ISSUE TITLE
Addition of .gitignore

### ISSUE THREAD

**Issue by ruppysuppy** [surdebmalya/First-Project-On-Django#1]
Add .gitignore file to ignore the commiting of redundant files like cache and important data files like the database

**Comment by surdebmalya** [comment]
> Add .gitignore file to ignore the commiting of redundant files like cache and important data files like the database

I just add .gitignore file with two components __pycache__ and db.sqlite3
Please check now...

**Comment by ruppysuppy** [comment]
Delete the `__pycache__` from [mysite](https://github.com/surdebmalya/First-Project-On-Django/tree/master/mysite) and use

```
# SQLite Database files
*.sqlite3

# Byte-compiled / optimized / DLL files
__pycache__/
*/__pycache__/*
*.py[cod]
*.pyo
*.pyc
```

**Comment by surdebmalya** [comment]
> Delete the `__pycache__` from [mysite](https://github.com/surdebmalya/First-Project-On-Django/tree/master/mysite) and use
> 
> ```
> # SQLite Database files
> *.sqlite3
> 
> # Byte-compiled / optimized / DLL files
> __pycache__/
> */__pycache__/*
> *.py[cod]
> *.pyo
> *.pyc
> ```

I have uploaded all, please check it!!!....

**Comment by ruppysuppy** [comment]
Yep, its done
